"""empty message

Revision ID: 65a9281ea34a
Revises: 28c1feec34a8
Create Date: 2022-05-31 20:15:51.442925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65a9281ea34a'
down_revision = '28c1feec34a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_username'), 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_username'), 'users', type_='unique')
    # ### end Alembic commands ###
